import type { Metadata } from "next";
import "../globals.css";
import { SignalRProvider } from "../lib/SignalRProvider";
import { PropertyProvider } from "../context/PropertyContext";

export const metadata: Metadata = {
  title: "Valet Parking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <PropertyProvider>
        <SignalRProvider>
          <main>{children}</main>
        </SignalRProvider>
      </PropertyProvider>
    </div>
  );
}
