import type { Metadata } from "next";
import "../globals.css";
import Header from "@/app/components/Header";

export const metadata: Metadata = {
  title: "Valet Parking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-[100vh]">
      <Header />
      <main>{children}</main>
    </div>
  );
}
