const countries = [
    // North America & Caribbean (NANP)
    { id: "us", number: "+1", name: "United States", flag: "🇺🇸" },
    { id: "ca", number: "+1", name: "Canada", flag: "🇨🇦" },
    { id: "ag", number: "+1", name: "Antigua & Barbuda", flag: "🇦🇬" },
    { id: "bs", number: "+1", name: "Bahamas", flag: "🇧🇸" },
    { id: "bb", number: "+1", name: "Barbados", flag: "🇧🇧" },
    { id: "dm", number: "+1", name: "Dominica", flag: "🇩🇲" },
    { id: "gd", number: "+1", name: "Grenada", flag: "🇬🇩" },
    { id: "jm", number: "+1", name: "Jamaica", flag: "🇯🇲" },
    { id: "kn", number: "+1", name: "Saint Kitts & Nevis", flag: "🇰🇳" },
    { id: "lc", number: "+1", name: "Saint Lucia", flag: "🇱🇨" },
    { id: "vc", number: "+1", name: "Saint Vincent & Grenadines", flag: "🇻🇨" },
    { id: "tt", number: "+1", name: "Trinidad & Tobago", flag: "🇹🇹" },
    { id: "pr", number: "+1", name: "Puerto Rico", flag: "🇵🇷" },
    { id: "do", number: "+1", name: "Dominican Republic", flag: "🇩🇴" },
  
    // Europe
    { id: "eg", number: "+20", name: "Egypt", flag: "🇪🇬" },
    { id: "gr", number: "+30", name: "Greece", flag: "🇬🇷" },
    { id: "nl", number: "+31", name: "Netherlands", flag: "🇳🇱" },
    { id: "be", number: "+32", name: "Belgium", flag: "🇧🇪" },
    { id: "fr", number: "+33", name: "France", flag: "🇫🇷" },
    { id: "es", number: "+34", name: "Spain", flag: "🇪🇸" },
    { id: "hu", number: "+36", name: "Hungary", flag: "🇭🇺" },
    { id: "it", number: "+39", name: "Italy", flag: "🇮🇹" },
    { id: "ro", number: "+40", name: "Romania", flag: "🇷🇴" },
    { id: "ch", number: "+41", name: "Switzerland", flag: "🇨🇭" },
    { id: "at", number: "+43", name: "Austria", flag: "🇦🇹" },
    { id: "gb", number: "+44", name: "United Kingdom", flag: "🇬🇧" },
    { id: "dk", number: "+45", name: "Denmark", flag: "🇩🇰" },
    { id: "se", number: "+46", name: "Sweden", flag: "🇸🇪" },
    { id: "no", number: "+47", name: "Norway", flag: "🇳🇴" },
    { id: "pl", number: "+48", name: "Poland", flag: "🇵🇱" },
    { id: "de", number: "+49", name: "Germany", flag: "🇩🇪" },
  
    // Asia
    { id: "my", number: "+60", name: "Malaysia", flag: "🇲🇾" },
    { id: "au", number: "+61", name: "Australia", flag: "🇦🇺" },
    { id: "id", number: "+62", name: "Indonesia", flag: "🇮🇩" },
    { id: "ph", number: "+63", name: "Philippines", flag: "🇵🇭" },
    { id: "nz", number: "+64", name: "New Zealand", flag: "🇳🇿" },
    { id: "sg", number: "+65", name: "Singapore", flag: "🇸🇬" },
    { id: "th", number: "+66", name: "Thailand", flag: "🇹🇭" },
    { id: "jp", number: "+81", name: "Japan", flag: "🇯🇵" },
    { id: "kr", number: "+82", name: "South Korea", flag: "🇰🇷" },
    { id: "vn", number: "+84", name: "Vietnam", flag: "🇻🇳" },
    { id: "cn", number: "+86", name: "China", flag: "🇨🇳" },
    { id: "in", number: "+91", name: "India", flag: "🇮🇳" },
    { id: "pk", number: "+92", name: "Pakistan", flag: "🇵🇰" },
    { id: "af", number: "+93", name: "Afghanistan", flag: "🇦🇫" },
    { id: "lk", number: "+94", name: "Sri Lanka", flag: "🇱🇰" },
    { id: "mm", number: "+95", name: "Myanmar", flag: "🇲🇲" },
    { id: "ir", number: "+98", name: "Iran", flag: "🇮🇷" },
  
    // Middle East
    { id: "tr", number: "+90", name: "Türkiye (Turkey)", flag: "🇹🇷" },
    { id: "lb", number: "+961", name: "Lebanon", flag: "🇱🇧" },
    { id: "jo", number: "+962", name: "Jordan", flag: "🇯🇴" },
    { id: "sy", number: "+963", name: "Syria", flag: "🇸🇾" },
    { id: "iq", number: "+964", name: "Iraq", flag: "🇮🇶" },
    { id: "kw", number: "+965", name: "Kuwait", flag: "🇰🇼" },
    { id: "sa", number: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
    { id: "ye", number: "+967", name: "Yemen", flag: "🇾🇪" },
    { id: "om", number: "+968", name: "Oman", flag: "🇴🇲" },
    { id: "ps", number: "+970", name: "Palestine", flag: "🇵🇸" },
    { id: "ae", number: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
    { id: "il", number: "+972", name: "Israel", flag: "🇮🇱" },
    { id: "bh", number: "+973", name: "Bahrain", flag: "🇧🇭" },
    { id: "qa", number: "+974", name: "Qatar", flag: "🇶🇦" },
  
    // Africa (sample subset)
    { id: "ss", number: "+211", name: "South Sudan", flag: "🇸🇸" },
    { id: "ma", number: "+212", name: "Morocco", flag: "🇲🇦" },
    { id: "dz", number: "+213", name: "Algeria", flag: "🇩🇿" },
    { id: "tn", number: "+216", name: "Tunisia", flag: "🇹🇳" },
    { id: "ly", number: "+218", name: "Libya", flag: "🇱🇾" },
    { id: "gh", number: "+233", name: "Ghana", flag: "🇬🇭" },
    { id: "ng", number: "+234", name: "Nigeria", flag: "🇳🇬" },
    { id: "cm", number: "+237", name: "Cameroon", flag: "🇨🇲" },
    { id: "za", number: "+27", name: "South Africa", flag: "🇿🇦" },
  
    // Central & South America (sample subset)
    { id: "pe", number: "+51", name: "Peru", flag: "🇵🇪" },
    { id: "mx", number: "+52", name: "Mexico", flag: "🇲🇽" },
    { id: "cu", number: "+53", name: "Cuba", flag: "🇨🇺" },
    { id: "ar", number: "+54", name: "Argentina", flag: "🇦🇷" },
    { id: "br", number: "+55", name: "Brazil", flag: "🇧🇷" },
    { id: "cl", number: "+56", name: "Chile", flag: "🇨🇱" },
    { id: "co", number: "+57", name: "Colombia", flag: "🇨🇴" },
    { id: "ve", number: "+58", name: "Venezuela", flag: "🇻🇪" },
    { id: "uy", number: "+598", name: "Uruguay", flag: "🇺🇾" },
  
    // Pacific / Others (sample subset)
    { id: "nf", number: "+672", name: "Norfolk Island", flag: "🇳🇫" },
    { id: "bn", number: "+673", name: "Brunei", flag: "🇧🇳" },
    { id: "nr", number: "+674", name: "Nauru", flag: "🇳🇷" },
    { id: "pg", number: "+675", name: "Papua New Guinea", flag: "🇵🇬" },
    { id: "to", number: "+676", name: "Tonga", flag: "🇹🇴" },
    { id: "sb", number: "+677", name: "Solomon Islands", flag: "🇸🇧" },
    { id: "vu", number: "+678", name: "Vanuatu", flag: "🇻🇺" },
    { id: "fj", number: "+679", name: "Fiji", flag: "🇫🇯" },
    { id: "pw", number: "+680", name: "Palau", flag: "🇵🇼" },
    { id: "ws", number: "+685", name: "Samoa", flag: "🇼🇸" },
    { id: "ki", number: "+686", name: "Kiribati", flag: "🇰🇮" },
    { id: "nc", number: "+687", name: "New Caledonia", flag: "🇳🇨" },
    { id: "tv", number: "+688", name: "Tuvalu", flag: "🇹🇻" },
    { id: "pf", number: "+689", name: "French Polynesia", flag: "🇵🇫" },
    { id: "fm", number: "+691", name: "Micronesia", flag: "🇫🇲" },
    { id: "mh", number: "+692", name: "Marshall Islands", flag: "🇲🇭" },
  ];
  
  export default countries;
  